name: 'greeting'
description: 'Hello World!'
inputs:
  who-to-greet:
    description: 'Name of person who to send greetings'
    default: 'Ningaraj Siddegowda'
    required: true
outputs:
  time:
    description: 'When I have greeted'
runs:
  using: 'node12'
  main: 'index.js'